CC:=gcc

fopen_test: fopen_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@
# $@表示当前target目标文件的名称，此处是fopen_test
# $^表示当前target所有依赖文件列表，此处是fopen_test.c

fclose_test: fclose_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputc_test: fputc_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputs_test: fputs_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fprintf_test: fprintf_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgetc_test: fgetc_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgets_test: fgets_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fscanf_test: fscanf_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

stdin_out_err_test: stdin_out_err_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@